### 스칼라(0D텐서)

In [2]:
import numpy as np
x = np.array(12)
print('x :',x)
print('x.ndim :',x.ndim)

x : 12
x.ndim : 0


### 벡터(1D텐서)

In [3]:
x = np.array([96,1,6,40,27])
print('x :',x)
print('x.ndim :',x.ndim)

x : [96  1  6 40 27]
x.ndim : 1


### 행렬(2D텐서)

In [4]:
x = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]])
print('x :',x)
print('x.ndim :',x.ndim)

x : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
x.ndim : 2


### 고차원 텐서(3D텐서~)

In [5]:
x = np.array([[[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]],
            [[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]],
            [[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]]])
print('x :',x)
print('x.ndim :',x.ndim)

x : [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
x.ndim : 3


### 배치데이터

In [6]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


In [7]:
batch = train_images[:128] #첫번째 배치
batch = train_images[128:256] #두번째 배치
batch = train_images[128*n:128*(n+1)] #n번째 배치

### 텐서의 실제 사례

벡터 데이터 : (samples, features) 크기의 2D텐서\
시계열 데이터 : (samples, timesteps, features) 크기의 3D텐서\
이미지 데이터 : (samples, height, width, channels) 또는 (samples, channels, height, width) 크기의 4D텐서\
동영상 : (samples, frames, height, width, channels) 또는 (samples, frames, channels, height, width) 크기의 5D텐서