In [1]:
import numpy as np
np.__version__

'1.18.2'

ndarray 개요

In [3]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태 :', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태 : (3,)


In [4]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태 :', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)


In [5]:
array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태 :', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)


In [6]:
print(f'array1:{array1.ndim}차원, array2:{array2.ndim}차원, array3:{array3.ndim}차원')

array1:1차원, array2:2차원, array3:2차원


ndarray 데이터 타입

In [7]:
list = [1,2,3]
print(type(list))
array = np.array(list)
print(type(array))
print(array, array.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [8]:
list = [1,2,'test']
print(type(list))
array = np.array(list)
print(type(array))
print(array, array.dtype)

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' 'test'] <U11


In [10]:
list = [1,2,3.0]
print(type(list))
array = np.array(list)
print(type(array))
print(array, array.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1. 2. 3.] float64


In [11]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


ndarray를 편리하게 생성하기

In [13]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [14]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [17]:
array1 = np.arange(10)
print('array1 :\n', array1)

array2 = array1.reshape(2,5)
print('array2 :\n', array2)

array3 = array1.reshape(5,2)
print('array3 :\n', array3)

array1 :
 [0 1 2 3 4 5 6 7 8 9]
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
array2 = array1.reshape(-1,5)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
array3 = array1.reshape(-1,1)
print(array3)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [22]:
array4 = array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [23]:
array2 = array1.reshape(2, -1)
print(array2)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
array3.ndim

2

In [27]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


ndarray 데이터 세트 선택하기 - 인덱싱

In [2]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print(array2d[2,2])
print(array2d[0,0])
print(array2d[1,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
4


----------

ndarray에서 row와 col은 사용하지 않음\
행렬은 2차원이기 때문에 axis0과 axis1로 구분되는 것이 맞음\
[row = 0, col=1]\
[axis0=0, axis1=1]

----------

슬라이싱

In [4]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
array4 = array1[:3]
print(array4)
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [9]:
array2d = array1.reshape(3,3)
print(array2d)
print(array2d[0:2,0:2])
print(array2d[1:3,0:3])
print(array2d[1:3,:])
print(array2d[:,:])
print(array2d[:2,1:])
print(array2d[:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]


In [10]:
print(array2d[0])
print(array2d[0].shape)
#뒤에 오는 인덱스를 없애면 n-1차원으로 반환함
#ex) 3차원 ndarray에서 뒤에오는 인덱스를 없애면 2차원 반환

[1 2 3]
(3,)


In [15]:
array3 = array2d[[0,1],2]
print(array3.tolist())

array4 = array2d[[0,1],0:2]
print(array4.tolist())

array5 = array2d[[0,1]]
print(array5.tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


불린 인덱싱

In [18]:
array3 = array1d[array1d>5]
print(array3)
print(array1d>5)

[6 7 8 9]
[False False False False False  True  True  True  True]


In [19]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


행렬의 정렬 -sort(), argsort()

In [20]:
org_array=np.array([3,1,9,5])
print(f'원본행렬:{org_array}')

원본행렬:[3 1 9 5]


In [22]:
#np.sort()로 정렬
sort_array1=np.sort(org_array)
print(f'np.sort()호출 후 반환된 정렬 행렬:{sort_array1}')
print(f'원본행렬:{org_array}')

np.sort()호출 후 반환된 정렬 행렬:[1 3 5 9]
원본행렬:[3 1 9 5]


In [23]:
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print(f'org_array.sort()호출 후 반환된 행렬:{sort_array2}')
print(f'원본행렬:{org_array}')

org_array.sort()호출 후 반환된 행렬:None
원본행렬:[1 3 5 9]


In [24]:
sort_array1_desc = np.sort(org_array)[::-1]
print(f'내림차순 정렬:{sort_array1_desc}')

내림차순 정렬:[9 5 3 1]


In [28]:
array2d = np.array([[18,12],
                   [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [18 12]]
[[12 18]
 [ 1  7]]


In [29]:
org_array=np.array([3,1,9,5])
sort_indexes = np.argsort(org_array)
print(type(sort_indexes))
print(f'행렬 정렬시 원본 행렬의 인덱스:{sort_indexes}')

<class 'numpy.ndarray'>
행렬 정렬시 원본 행렬의 인덱스:[1 0 3 2]


In [30]:
org_array=np.array([3,1,9,5])
sort_indexes = np.argsort(org_array)[::-1]
print(type(sort_indexes))
print(f'행렬 내림차순 정렬시 원본 행렬의 인덱스:{sort_indexes}')

<class 'numpy.ndarray'>
행렬 내림차순 정렬시 원본 행렬의 인덱스:[2 3 0 1]


argsort()는 넘파이에서 활용도가 높음\
이유는 ndarray는 Dataframe의 칼럼과 같은 메타데이터를 가질 수 없기 때문에,\
짝이 있는 데이터(이름:성적 등)도 각각의 ndarray로 저장함\
하나의 ndarray를 기준으로 값을 정렬한 뒤, 그에 맞는 짝(ex 이름)을 찾아 출력할 때 argsort()로 반환된 인덱스묶음을 팬시 인덱스로 적용함

ex)성적을 내림차순으로 정렬 후, 성적과 매치되는 이름도 인덱스를 활용해 정렬 후 출력

In [34]:
name_array=np.array(['화신','익준','정석','납득','시경'])
score_array=np.array([9,8,10,5,7])

sort_indexes_desc = np.argsort(score_array)[::-1]
print(f'성적순 인덱스:{sort_indexes_desc}')
print(f'성적순 이름:{name_array[sort_indexes_desc]}')

성적순 인덱스:[2 0 1 4 3]
성적순 이름:['정석' '화신' '익준' '시경' '납득']


선형대수 연산 - 행렬 내적(행렬 곱)과 전치행렬 구하기

In [35]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

In [36]:
dot_product = np.dot(A,B)
print(f'행렬 내적 결과:\n{dot_product}')

행렬 내적 결과:
[[ 58  64]
 [139 154]]


In [40]:
transpose_mat = np.transpose(A)

print(f'A전치행렬:\n{transpose_mat}')
print(A.shape)
print(transpose_mat.shape)

A전치행렬:
[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(3, 2)
